apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wf-
  namespace: notebook
spec:
  entrypoint: dag
  templates:
  {% for job in jobs %}
  - name: {{ job['name'] }}
    container:
      image: cart.lge.com/lgebigdata/single-user:ssh
      command: {{ job['command'] }}
      workingDir: {{ workingDir }}
      securityContext:
        runAsUser: {{ runAsUser }}
      env:
      - name: JUPYTERHUB_USER
        value: {{ username }}
      - name: PATH
        value: {{ PATH }}
      resources:
        limits:
          cpu: "{{ limits['cpu'] }}"
          memory: "{{ limits['memory'] }}"
      volumeMounts:
      - mountPath: /home/jovyan
        name: home-vol
      - mountPath: /nas001
        name: nas001
  {% endfor %}
  - name: dag
    dag:
      tasks:
      {% for job in jobs %}
      - name: {{ job['name'] }}
        template: {{ job['name'] }}
        dependencies: {{ job['dependencies']}}
      {% endfor %}
  volumes:
  - name: home-vol
    persistentVolumeClaim:
      claimName: claim-{{ escaped_name }}
  - name: nas001
    persistentVolumeClaim:
      claimName: nas001
  nodeSelector:
   isctl: "true"